### ISSUE TITLE
macos12.1 Safari浏览器不能自动联播  

### ISSUE THREAD

**Issue by OctoberCool** [qier222/YesPlayMusic#1459] opened 2022-04-01 02:29 UTC
### 反馈 bug 需要的信息

网页版
macos12.1 Safari浏览器不能自动联播
翻看之前其他人的问题，也有提到过浏览器不能自动联播，包括谷歌浏览器，iPadOS15.1的safari浏览器，希望可以得到解决

控制台
`[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p1.music.126.net/ptDnCnaLlFRv42ifaOQPzg==/109951164346121606.jpg?param=512y512. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p4.music.126.net/UeTuwE7pvjBpypWLudqukA==/3132508627578625.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p3.music.126.net/pgUS3r30qUKkCEsW0X3kcg==/109951165325440019.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p3.music.126.net/2zKMCYP_vUyWUUxN3M56kA==/109951164484563377.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p3.music.126.net/PTGt8K1JgmUMxbQ3_10orA==/109951165597801424.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p4.music.126.net/vH9OBZrkFsBiGjNyrF0LjA==/109951165422272253.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p4.music.126.net/ZnJxTtQAxrrqT4mnoZ6SoA==/109951163092546134.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p3.music.126.net/-3KdDlsuSPXTfT59dyNL4w==/109951163359548958.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p4.music.126.net/sMvNgKL0EwlsomFrT1lOjA==/5796625301757325.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p4.music.126.net/C0XOiNcHcjCvIVrF3wV5Iw==/7698780420211208.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p3.music.126.net/PGtMwPY9BhhlXvdTxpcxDQ==/7929677860965773.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p3.music.126.net/OSiPuM2BOCEdLXuDc8KOjw==/3368903627889465.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p4.music.126.net/omOpdy7nMIgKBuHijF-MJA==/7935175419463193.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p4.music.126.net/PwqflWzlTTHX0GtjIBvAHg==/19104014532642654.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p3.music.126.net/tyOXJ8U9TisNRfcorQ-4og==/109951163050074297.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p3.music.126.net/jEmGso6Etp6OQwwsM-z00g==/109951163011334363.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p3.music.126.net/Ir7TdnbHGOVuED6pPGkLTw==/2908208256439252.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p4.music.126.net/poVOuaCxrC0HB_zPpvXEiQ==/109951163115263393.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p3.music.126.net/MK9Xke5gifBzl8K2kMPC_w==/1313916395226393.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p4.music.126.net/8MPGEc_yRldzUFi4WHxrww==/109951167216620686.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p3.music.126.net/9ZHQfMtTPjDgPJTY2kfTWw==/3225967116240087.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p4.music.126.net/6jt922VYf1X6T7tm3pSQng==/3331520232351413.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p3.music.126.net/r1pldmZEIwguVnJ6PdoAdw==/109951163131946802.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p4.music.126.net/JLRx8y4nkis57ffBQRIPzA==/109951163251167645.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p3.music.126.net/DdJkjIxIHjjV3LqdVDPKuA==/7913185185980834.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p3.music.126.net/hqSEb8ZXvHPCSLjJBv_ylQ==/3431575796308018.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p4.music.126.net/-knXfhIMvLOknV519O5vHA==/18753270325235270.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p4.music.126.net/sGeHoi0lTtMgRUbIMAacHQ==/109951163640420885.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p4.music.126.net/8RXYg86nX38RHsI9p0RF3A==/18722483998509930.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p4.music.126.net/kqDaIXnUN01dcIVunUOoUA==/18702692789739767.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p3.music.126.net/-vPKRtOyRYytQopvc6PRdw==/3368903627962451.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p3.music.126.net/UeTuwE7pvjBpypWLudqukA==/3132508627578625.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p4.music.126.net/pgUS3r30qUKkCEsW0X3kcg==/109951165325440019.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p4.music.126.net/2zKMCYP_vUyWUUxN3M56kA==/109951164484563377.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p3.music.126.net/ZnJxTtQAxrrqT4mnoZ6SoA==/109951163092546134.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p4.music.126.net/-3KdDlsuSPXTfT59dyNL4w==/109951163359548958.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p3.music.126.net/sMvNgKL0EwlsomFrT1lOjA==/5796625301757325.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p3.music.126.net/C0XOiNcHcjCvIVrF3wV5Iw==/7698780420211208.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p4.music.126.net/OSiPuM2BOCEdLXuDc8KOjw==/3368903627889465.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p4.music.126.net/jEmGso6Etp6OQwwsM-z00g==/109951163011334363.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p4.music.126.net/MK9Xke5gifBzl8K2kMPC_w==/1313916395226393.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p3.music.126.net/8MPGEc_yRldzUFi4WHxrww==/109951167216620686.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p4.music.126.net/9ZHQfMtTPjDgPJTY2kfTWw==/3225967116240087.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p4.music.126.net/r1pldmZEIwguVnJ6PdoAdw==/109951163131946802.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p3.music.126.net/JLRx8y4nkis57ffBQRIPzA==/109951163251167645.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p4.music.126.net/DdJkjIxIHjjV3LqdVDPKuA==/7913185185980834.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p4.music.126.net/hqSEb8ZXvHPCSLjJBv_ylQ==/3431575796308018.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p3.music.126.net/-knXfhIMvLOknV519O5vHA==/18753270325235270.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p4.music.126.net/-vPKRtOyRYytQopvc6PRdw==/3368903627962451.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p3.music.126.net/2zKMCYP_vUyWUUxN3M56kA==/109951164484563377.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p4.music.126.net/PTGt8K1JgmUMxbQ3_10orA==/109951165597801424.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p3.music.126.net/vH9OBZrkFsBiGjNyrF0LjA==/109951165422272253.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p4.music.126.net/ZnJxTtQAxrrqT4mnoZ6SoA==/109951163092546134.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p4.music.126.net/sMvNgKL0EwlsomFrT1lOjA==/5796625301757325.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p4.music.126.net/PGtMwPY9BhhlXvdTxpcxDQ==/7929677860965773.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p3.music.126.net/omOpdy7nMIgKBuHijF-MJA==/7935175419463193.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p4.music.126.net/tyOXJ8U9TisNRfcorQ-4og==/109951163050074297.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p3.music.126.net/jEmGso6Etp6OQwwsM-z00g==/109951163011334363.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p4.music.126.net/Ir7TdnbHGOVuED6pPGkLTw==/2908208256439252.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p3.music.126.net/9ZHQfMtTPjDgPJTY2kfTWw==/3225967116240087.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p3.music.126.net/6jt922VYf1X6T7tm3pSQng==/3331520232351413.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p4.music.126.net/JLRx8y4nkis57ffBQRIPzA==/109951163251167645.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p3.music.126.net/DdJkjIxIHjjV3LqdVDPKuA==/7913185185980834.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p3.music.126.net/hqSEb8ZXvHPCSLjJBv_ylQ==/3431575796308018.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p4.music.126.net/-knXfhIMvLOknV519O5vHA==/18753270325235270.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p3.music.126.net/sGeHoi0lTtMgRUbIMAacHQ==/109951163640420885.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] The page at https://music.qier222.com/library was allowed to display insecure content from http://p3.music.126.net/kqDaIXnUN01dcIVunUOoUA==/18702692789739767.jpg?param=224y224. (chunk-vendors.1f3bf974.js, line 39)

[Warning] HTML5 Audio pool exhausted, returning potentially locked audio object. (chunk-vendors.1f3bf974.js, line 17)`

**Comment by memorydream** [comment] 2022-04-01 06:25
Duplicate of #1408

**Closed by memorydream** 2022-04-01 06:25 UTC
