### ISSUE TITLE
在客户端win测试版0.4.4中出现JavaScript error

### ISSUE THREAD

**Issue by NingJay** [qier222/YesPlayMusic#1321] opened 2022-02-19 14:07 UTC
![image](https://user-images.githubusercontent.com/88469454/154804193-6b540630-c08f-4629-a51e-3760ddd20731.png)

**Comment by pan93412** [comment] 2022-02-19 14:08
duplicate of #1145

**Closed by pan93412** 2022-02-19 14:08 UTC
