### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by ximu227** [qier222/YesPlayMusic#1360] opened 2022-02-27 16:41 UTC
A,JavaScript error occurred in the main process
Uncaught Exception:
Error: EBADF: bad fle descriptor, write
et ObjectwriteSync (fs.js:711:3)
et ectualWrite (C\Users\中文用户名
\AppData\Local\Temp\24bV9DoEPFbAJgNnuSnMPb4mnM\resources\app.asar\,:26)
at SonicBoom.write (C;\Users\中文用户名
WAppDate\LecelNTemp\24bV@DcEPFbAJgNnu5nMVPb.4mrMresc
at Objectwrite (CAUsers\中文用户名
\AppDataLocal\Temp\24bV9DoEPFbAJgNnu5nlMPb4mnjWresources\app.asar.:12)
et Pinowrite (CA\Users\中文用户名
\AppDataMLocaMTemp\24bVeDoEPFbAJg[NnuSnMPb4mnjWresounces\app.asar..:15)
at Pino.LOG [as warn] (C\Users\中文用户名
\AppData\Loca\Temp\24bVSDoEPFbAJgNnu5nMPb4mnjMMresources\app.asary.21)
at ClientRequest.<anonymous> (CMUsers\中文用户名
\AppData\LocsMTemp\24bVSDoEPfbAlgNnusnMPb4mnM\resources\epp.assr,:12)
st ObjectenceWrapper (events.jis:421:28)
at ClientRequest.emit (events.js:315:20)
at Soclket.emitfequestTimeout (htpLcllentjs:784:9)

打游戏时听歌有时会报错，主界面会变黑，弹窗内容在上面（无法复制内容，ocr识别的也不是很准确，大概是这样）

**Comment by pan93412** [comment] 2022-02-27 16:42
Duplicate of #1145

**Closed by pan93412** 2022-02-27 16:42 UTC
