### ISSUE TITLE
🐛[BUG] 播放无版权或收费歌曲时错误

### ISSUE THREAD

**Issue by Jo-Joestar** [qier222/YesPlayMusic#1442] opened 2022-03-26 07:32 UTC
### 📄 [异常/日志]信息([Exception/Log] Information)

A JavaScript error occurred in the main process
Uncaught Exception:
Error: EBADF: bad file descriptor, write 
at Object.writeSync (fs.js:711:3)
at actualWrite(C:\Program Files\YesPlayMusic\resources\app.asar\node_modules\sonic-boom\index.js:349:26)
at SonicBoom.write (C:\Program Files\YesPlayMusic\resources\app.asar\node_modules\sonic-boom\index.js:218:5)
at Object.write (C:\Program Files\YesPlayMusic\resources\app.asar\node_modules\pino\lib\tools.js:286:12)
at Pino.write(C:\Program Files\YesPlayMusic\resources\app.asar\node_modules\pino\lib\proto.js:213:15)
at Pino.LOG [as warn](C:\Program Files\YesPlayMusic\resources\app.asar\node_modules\pinol\lib\tools.js:55:21)
at ClientRequest. <anonymous>(C:\Program Files\YesPlayMusic\resources\app.asar\node_modules\@unblockneteasemusic\...:12)
at Object.onceWrapper (events.js:421:28)
at ClientRequest.emit (events.js:315:20)
at Socket.emitRequestTimeout (_http_client.js:784:9)

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):0.4.3安装版
- 系统版本号(OS Version): Win10 21H2

### 🖼 截图(Screenshots)

![图片1](https://user-images.githubusercontent.com/59140208/160229641-dd80dfaf-61a1-429c-b736-134665da4c2d.png)

**Comment by pan93412** [comment] 2022-03-26 11:51
Duplicate of #1145

**Closed by pan93412** 2022-03-26 11:51 UTC
