### ISSUE TITLE
疑似unblockneteasemusic错误

### ISSUE THREAD

**Issue by stevensane520** [qier222/YesPlayMusic#1400] opened 2022-03-10 02:17 UTC
- 客户端 V0.4.3
- win11专业版 21H2 OS：22000.527
![image](https://user-images.githubusercontent.com/97885306/157574923-fdd95667-f46a-4310-bbf0-8c96f5b365db.png)
![image](https://user-images.githubusercontent.com/97885306/157574934-d50311e0-397e-45ec-adf1-5f1a62ede7ae.png)

**Comment by pan93412** [comment] 2022-03-10 02:42
Duplicate of #1145

**Closed by pan93412** 2022-03-10 02:42 UTC
