### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by garfieldkai** [qier222/YesPlayMusic#1252] opened 2022-01-20 07:02 UTC
windows客户端，版本0.4.3
启动弹出对话框，报错

![image](https://user-images.githubusercontent.com/11343590/150289409-8b27d68a-c4e0-48de-88d3-4ddf5924c2d3.png)

**Comment by pan93412** [comment] 2022-01-20 07:04
Duplicate of #1145

**Closed by pan93412** 2022-01-20 07:04 UTC
