### ISSUE TITLE
启动后弹出频繁弹出Java错误提示

### ISSUE THREAD

**Issue by Capricornsong** [qier222/YesPlayMusic#1371] opened 2022-03-03 22:48 UTC
- 客户端
- Win 10 21H2
![image](https://user-images.githubusercontent.com/45059424/156665754-ed4a4d57-7c28-4b7f-9639-c01549e97417.png)

**Comment by memorydream** [comment] 2022-03-04 03:05
Duplicate of #1145

**Closed by memorydream** 2022-03-04 03:05 UTC
