### ISSUE TITLE
音质切换FLAC后提示错误切无法切换至FLAC

### ISSUE THREAD

**Issue by misaka20002** [qier222/YesPlayMusic#1327] opened 2022-02-21 06:28 UTC
- 客户端 YesPlayMusic-0.4.4.exe
- win10 21H2

![image](https://user-images.githubusercontent.com/40714502/154900522-39615d2e-d19e-40ab-b4e5-efb4154f7371.png)

**Comment by memorydream** [comment] 2022-02-21 07:28
Duplicate of #1145

**Closed by memorydream** 2022-02-21 07:28 UTC
