### ISSUE TITLE
javascript error

### ISSUE THREAD

**Issue by Heporis** [qier222/YesPlayMusic#1416] opened 2022-03-16 20:54 UTC
听一会儿就报错，关了立马又来了![image](https://user-images.githubusercontent.com/51895154/158689028-3c988f6d-d246-49c1-bcfb-a6c11345bf46.png)

**Comment by memorydream** [comment] 2022-03-16 21:58
Duplicate of #1145

**Closed by memorydream** 2022-03-16 21:58 UTC
Labels: duplicate
