### ISSUE TITLE
自己上传的歌曲（音乐云盘歌曲）播放异常

### ISSUE THREAD

**Issue by LTHPKBTE** [qier222/YesPlayMusic#586] opened 2021-04-23 12:30 UTC
客户端 Win10 21H1(19043.906)
播放到歌单中自己上传的文件时会停止播放，暂停再播放会跳回上一首歌，但是歌名等各种信息都没变，只有歌曲本身变了，而且播放到上一首歌结束就会再次卡在自己上传的歌的0分0秒。
![图片](https://user-images.githubusercontent.com/53574505/115870694-2cd02e80-a472-11eb-8912-24df49f0b99c.png)
（正在播放上一首歌）

控制台报错：
<details>
<summary>[Console]</summary>
chunk-vendors.47cdb8e4.js:50 Fetch API cannot load app://./service-worker.js. URL scheme "app" is not supported.

index.d2ce843c.js:1 Error during service worker registration: TypeError: Failed to fetch
    at u (chunk-vendors.47cdb8e4.js:50)
    at chunk-vendors.47cdb8e4.js:50
chunk-vendors.47cdb8e4.js:45 Unhandled rejection: TypeError: Cannot read property '0' of undefined
    at h (app://./js/index.d2ce843c.js:1:121639)
    at app://./js/index.d2ce843c.js:1:24591
From previous: 
    at qt.n (app://./js/chunk-vendors.47cdb8e4.js:45:59720)
    at Proxy.value (app://./js/index.d2ce843c.js:1:25065)
    at app://./js/index.d2ce843c.js:1:26054
From previous: 
    at qt.n (app://./js/chunk-vendors.47cdb8e4.js:45:59720)
    at Proxy.value (app://./js/index.d2ce843c.js:1:24166)
    at Proxy.value (app://./js/index.d2ce843c.js:1:25026)
    at app://./js/index.d2ce843c.js:1:26054
From previous: 
    at qt.n (app://./js/chunk-vendors.47cdb8e4.js:45:59720)
    at f (app://./js/index.d2ce843c.js:1:122046)
    at Proxy.value (app://./js/index.d2ce843c.js:1:24162)
    at Proxy.value (app://./js/index.d2ce843c.js:1:25026)
    at app://./js/index.d2ce843c.js:1:26054
From previous: 
    at qt.n (app://./js/chunk-vendors.47cdb8e4.js:45:59720)
    at Object.t.get (app://./js/chunk-vendors.47cdb8e4.js:45:69374)
    at f (app://./js/index.d2ce843c.js:1:122031)
    at Proxy.value (app://./js/index.d2ce843c.js:1:24162)
    at Proxy.value (app://./js/index.d2ce843c.js:1:25026)
    at app://./js/index.d2ce843c.js:1:26054
From previous: 
    at qt.n (app://./js/chunk-vendors.47cdb8e4.js:45:59720)
    at Ce (app://./js/chunk-vendors.47cdb8e4.js:45:67857)
    at Object.t._trans (app://./js/chunk-vendors.47cdb8e4.js:45:69106)
    at Object.t.get (app://./js/chunk-vendors.47cdb8e4.js:45:69254)
    at f (app://./js/index.d2ce843c.js:1:122031)
    at Proxy.value (app://./js/index.d2ce843c.js:1:24162)
    at Proxy.value (app://./js/index.d2ce843c.js:1:25026)
    at app://./js/index.d2ce843c.js:1:26054
From previous: 
    at Object.t._promise (app://./js/chunk-vendors.47cdb8e4.js:45:93091)
    at Ce (app://./js/chunk-vendors.47cdb8e4.js:45:67776)
    at Object.t._trans (app://./js/chunk-vendors.47cdb8e4.js:45:69106)
    at Object.t.get (app://./js/chunk-vendors.47cdb8e4.js:45:69254)
    at f (app://./js/index.d2ce843c.js:1:122031)
    at Proxy.value (app://./js/index.d2ce843c.js:1:24162)
    at Proxy.value (app://./js/index.d2ce843c.js:1:25026)
    at app://./js/index.d2ce843c.js:1:26054
2

chunk-vendors.47cdb8e4.js:45 [VueSlider error]: The "value" must be less than or equal to the "max".

index.d2ce843c.js:1 Uncaught (in promise) TypeError: Cannot read property '0' of undefined
    at h (app://./js/index.d2ce843c.js:1:121639)
    at app://./js/index.d2ce843c.js:1:24591
From previous: 
    at qt.n (app://./js/chunk-vendors.47cdb8e4.js:45:59720)
    at Proxy.value (app://./js/index.d2ce843c.js:1:25065)
    at app://./js/index.d2ce843c.js:1:25665
From previous: 
    at qt.n (app://./js/chunk-vendors.47cdb8e4.js:45:59720)
    at Proxy.value (app://./js/index.d2ce843c.js:1:24166)
    at Proxy.value (app://./js/index.d2ce843c.js:1:25026)
    at app://./js/index.d2ce843c.js:1:25665
From previous: 
    at qt.n (app://./js/chunk-vendors.47cdb8e4.js:45:59720)
    at f (app://./js/index.d2ce843c.js:1:122046)
    at Proxy.value (app://./js/index.d2ce843c.js:1:24162)
    at Proxy.value (app://./js/index.d2ce843c.js:1:25026)
    at app://./js/index.d2ce843c.js:1:25665
From previous: 
    at qt.n (app://./js/chunk-vendors.47cdb8e4.js:45:59720)
    at Object.t.get (app://./js/chunk-vendors.47cdb8e4.js:45:69374)
    at f (app://./js/index.d2ce843c.js:1:122031)
    at Proxy.value (app://./js/index.d2ce843c.js:1:24162)
    at Proxy.value (app://./js/index.d2ce843c.js:1:25026)
    at app://./js/index.d2ce843c.js:1:25665
From previous: 
    at qt.n (app://./js/chunk-vendors.47cdb8e4.js:45:59720)
    at Ce (app://./js/chunk-vendors.47cdb8e4.js:45:67857)
    at Object.t._trans (app://./js/chunk-vendors.47cdb8e4.js:45:69106)
    at Object.t.get (app://./js/chunk-vendors.47cdb8e4.js:45:69254)
    at f (app://./js/index.d2ce843c.js:1:122031)
    at Proxy.value (app://./js/index.d2ce843c.js:1:24162)
    at Proxy.value (app://./js/index.d2ce843c.js:1:25026)
    at app://./js/index.d2ce843c.js:1:25665
From previous: 
    at Object.t._promise (app://./js/chunk-vendors.47cdb8e4.js:45:93091)
    at Ce (app://./js/chunk-vendors.47cdb8e4.js:45:67776)
    at Object.t._trans (app://./js/chunk-vendors.47cdb8e4.js:45:69106)
    at Object.t.get (app://./js/chunk-vendors.47cdb8e4.js:45:69254)
    at f (app://./js/index.d2ce843c.js:1:122031)
    at Proxy.value (app://./js/index.d2ce843c.js:1:24162)
    at Proxy.value (app://./js/index.d2ce843c.js:1:25026)
    at app://./js/index.d2ce843c.js:1:25665

DevTools failed to load SourceMap: Could not parse content for app://./js/index.d2ce843c.js.map: Unexpected end of JSON input

DevTools failed to load SourceMap: Could not parse content for app://./js/chunk-vendors.47cdb8e4.js.map: Unexpected end of JSON input

DevTools failed to load SourceMap: Could not parse content for app://./js/chunk-d4970822.058f27ab.js.map: Unexpected end of JSON input

DevTools failed to load SourceMap: Could not parse content for app://./js/chunk-1615d482.923286c8.js.map: Unexpected end of JSON input

DevTools failed to load SourceMap: Could not parse content for app://./js/chunk-570c23bc.509f4832.js.map: Unexpected end of JSON input

DevTools failed to load SourceMap: Could not parse content for app://./js/chunk-54adfd40.31f07347.js.map: Unexpected end of JSON input

www.google-analytics…_r=1&z=1460242461:1 Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
</details>

**Comment by lethefrost** [comment] 2021-04-29 22:53
mac也有此bug，似乎是最近两三个版本开始这样的

**Comment by LTHPKBTE** [comment] 2021-05-04 14:28
测试已修复。谢谢

**Comment by lethefrost** [comment] 2021-06-03 20:53
@qier222 不好意思打扰了，但是mac版好像还没修复……现在仍然不能播放。

**Comment by LTHPKBTE** [comment] 2021-08-04 15:26
嗯...确实又不行了....

**Comment by pan93412** [comment] 2022-04-23 07:43
Duplicate of #1236

**Closed by pan93412** 2022-04-23 07:43 UTC
Labels: bug
